Repository inTestiGator/pytest-focus, pull requests merged in 2019-05, with the labels that each got.

#24 Add more to README
  README.md
Labels: documentation, enhancement

#25 Doc checks
  README.md
Labels: documentation, enhancement

#26 Logo
  README.md
  static/focus-logo.png
Labels: enhancement

#29 Fix naming conventions
  src/pytest_focus.py
Labels: refactor

#31 Feature/focus notify
  src/pytest_focus.py
Labels: enhancement

#30 Add ability to send push notifications for failed test cases
  src/pytest_focus.py
Labels: enhancement

#36 Add module that allows for mac notifications to made
  src/mac-notifications.py
Labels: enhancement

#46 Add a Codacy badge to README.md
  README.md
Labels: documentation, enhancement

#49 Codacy additions
  .travis.yml
  Pipfile
  Pipfile.lock
Labels: documentation, enhancement, test

#50 Added new iteration of the Focus logo
  README.md
  static/focus-logo2.png
Labels: enhancement

#52 Improve Codacy rated code quality
  CONTRIBUTING.md
  README.md
Labels: refactor

#59 Feature/todo
  src/pytest_focus.py
Labels: refactor
